Repository apiato/core, pull requests merged in 2024-12, with the labels that each got.

#212 Refactor faker use
  src/Traits/TestTraits/PhpUnit/TestAuthHelperTrait.php
  tests/Infrastructure/Doubles/BookFactory.php
Labels: type: refactor

#194 fix: controller generator
  src/Generator/Commands/ContainerApiGenerator.php
  src/Generator/Commands/ContainerWebGenerator.php
  src/Generator/Commands/ControllerGenerator.php
Labels: type: fix

#214 fix(generator): Broken multi-action Controller generator
  src/Generator/Commands/ContainerApiGenerator.php
  src/Generator/Commands/RouteGenerator.php
  src/Generator/Stubs/controllers/api/crud.stub
  src/Generator/Stubs/routes/api.mac.stub
  src/Generator/Stubs/routes/api.sac.stub
  src/Generator/Stubs/routes/web.mac.stub
  src/Generator/Stubs/routes/web.sac.stub
Labels: type: fix

#216 fix(generator): Listeners are not added to EventServiceProvider
  src/Generator/Commands/ContainerApiGenerator.php
  src/Generator/Commands/ContainerGenerator.php
  src/Generator/Commands/ContainerWebGenerator.php
  src/Generator/Commands/EventGenerator.php
  src/Generator/Commands/ServiceProviderGenerator.php
  src/Generator/Stubs/listeners/listener.stub
  src/Generator/Stubs/providers/event-service-provider-with-listener.stub
  src/Generator/Stubs/providers/generic-event-service-provider.stub
  src/Generator/Stubs/providers/main-service-provider-with-event-provider.stub
  src/Generator/Stubs/providers/main-service-provider.stub
  src/Generator/Stubs/providers/middleware-service-provider.stub
Labels: type: enhancement, type: fix, type: refactor

#217 fix(generator): EventServiceProvider don't get registered correctly
  src/Generator/Commands/ContainerApiGenerator.php
  src/Generator/Commands/ServiceProviderGenerator.php
  src/Generator/Stubs/providers/main-service-provider-with-event-provider.stub
  src/Generator/Stubs/providers/main-service-provider.stub
Labels: type: fix

#206 refactor(API-1186): Simplify Passport installation in main TestCase
  src/Abstracts/Tests/PhpUnit/TestCase.php
  src/Traits/TestCaseTrait.php
Labels: type: breaking change, type: refactor
